import { IconName } from './icon.component';

/** სერვისების/წესების picker-ისთვის შემოთავაზებული curated ნაკრები (UI-chrome icon-ები — chevron-*, external-link — გამორიცხულია). */
export const CURATED_ICONS: IconName[] = [
  'general',
  'concierge-bell',
  'cup',
  'cutlery',
  'bar',
  'droplet',
  'pool',
  'gym',
  'clock',
  'wifi',
  'ac',
  'tv',
  'safe',
  'minibar',
  'laundry',
  'elevator',
  'parking',
  'shuttle',
  'luggage',
  'bike',
  'beach',
  'kids-club',
  'pets',
  'non-smoking',
  'business-center',
  'accessibility',
  'shield-check',
  'map-pin',
  'phone'
];

export const ICON_LABELS: Partial<Record<IconName, string>> = {
  general: 'ზოგადი',
  'concierge-bell': 'კონსიერჟი',
  cup: 'საუზმე',
  cutlery: 'რესტორანი',
  bar: 'ბარი',
  droplet: 'Spa',
  pool: 'აუზი',
  gym: 'სავარჯიშო დარბაზი',
  clock: '24/7',
  wifi: 'Wi-Fi',
  ac: 'კონდიციონერი',
  tv: 'ტელევიზორი',
  safe: 'სეიფი',
  minibar: 'მინი-ბარი',
  laundry: 'სამრეცხაო',
  elevator: 'ლიფტი',
  parking: 'პარკინგი',
  shuttle: 'ტრანსფერი',
  luggage: 'ბარგი',
  bike: 'ველოსიპედი',
  beach: 'პლაჟი',
  'kids-club': 'საბავშვო კლუბი',
  pets: 'ცხოველები',
  'non-smoking': 'არამწეველთათვის',
  'business-center': 'ბიზნეს-ცენტრი',
  accessibility: 'ხელმისაწვდომობა',
  'shield-check': 'უსაფრთხოება',
  'map-pin': 'მდებარეობა',
  phone: 'კონტაქტი'
};
